assetic:
    assets:

        # CSS SECTION ##########################################################

        btn_admin_bootstrap_css:
            inputs:
                - @BtnAdminBundle/Resources/public/css/vendor/bootstrap/bootstrap.css
            output: css/btn-admin.bootstrap.css

        btn_admin_bootstrap_flat_css:
            inputs:
                - @BtnAdminBundle/Resources/public/css/vendor/bootflat/bootflat.css
                - @BtnAdminBundle/Resources/public/css/bootflat-custom.css
            output: css/btn-admin.bootstrap-flat.css

        btn_admin_bootstrap_theme_css:
            inputs:
                - @BtnAdminBundle/Resources/public/css/vendor/bootstrap/bootstrap-theme.css
            output: css/btn-admin.bootstrap-theme.css

        btn_admin_ladda_css:
            inputs:
                - @BtnAdminBundle/Resources/public/css/vendor/ladda-bootstrap/ladda-themeless.css
            output: css/btn-admin.ladda.css

        btn_admin_loading_css:
            inputs:
                - @btn_admin_ladda_css
            output: css/btn-admin.loading.css

        btn_admin_jstree_css:
            inputs:
                - @BtnAdminBundle/Resources/public/css/vendor/jstree/style.css
            output: css/btn-admin.jstree.css

        # JS SECTION ###########################################################

        btn_admin_app_js:
            inputs:
                - @btn_admin_pubsub_js
                - @BtnAdminBundle/Resources/public/js/app.js
            output: js/btn-admin.app.js

        btn_admin_jquery_js:
            inputs:
                - @BtnAdminBundle/Resources/public/js/vendor/jquery/jquery-1.11.1.js
            output: js/btn-admin.jquery.js

        btn_admin_bootstrap_js:
            inputs:
                - @BtnAdminBundle/Resources/public/js/vendor/bootstrap/bootstrap.js
            output: js/btn-admin.bootstrap.js

        btn_admin_confirm_js:
            inputs:
                - @BtnAdminBundle/Resources/public/js/vendor/bootbox.js/bootbox.js
                - @BtnAdminBundle/Resources/public/js/confirm.init.js
            output: js/btn-admin.confirm.js

        btn_admin_pubsub_js:
            inputs:
                - @BtnAdminBundle/Resources/public/js/vendor/pubsub-js/pubsub.js
            output: js/btn-admin.pubsub.js

        btn_admin_spin_js:
            inputs:
                - @BtnAdminBundle/Resources/public/js/vendor/spin.js/spin.js
                - @BtnAdminBundle/Resources/public/js/spin.init.js
            output: js/btn-admin.spin.js

        btn_admin_ladda_js:
            inputs:
                - @BtnAdminBundle/Resources/public/js/vendor/ladda-bootstrap/ladda.js
                - @BtnAdminBundle/Resources/public/js/ladda.init.js
            output: js/btn-admin.ladda.js

        btn_admin_loading_js:
            inputs:
                - @btn_admin_spin_js
                - @btn_admin_ladda_js
            output: js/btn-admin.loading.js

        btn_admin_jstree_js:
            inputs:
                - @BtnAdminBundle/Resources/public/js/vendor/jstree/jstree.js
                - @BtnAdminBundle/Resources/public/js/jstree.init.js
            output: js/btn-admin.jstree.js
