parameters:
    btn_admin.form.handler.entiy_form.class: Btn\AdminBundle\Form\Handler\EntityFormHandler
    btn_admin.form.handler.entiy_form.request_aware.class: Btn\AdminBundle\Form\Handler\EntityFormHandler
    btn_admin.form.button.create.class: Btn\AdminBundle\Form\Button\CreateButton
    btn_admin.form.button.delete.class: Btn\AdminBundle\Form\Button\DeleteButton
    btn_admin.form.button.save.class: Btn\AdminBundle\Form\Button\SaveButton
    btn_admin.form.button.update.class: Btn\AdminBundle\Form\Button\UpdateButton
    btn_admin.form.type.color.class: Btn\AdminBundle\Form\Type\ColorType
    btn_admin.form.type.date_time.class: Btn\AdminBundle\Form\Type\DateTimeType
    btn_admin.form.type.embeded.class: Btn\AdminBundle\Form\Type\EmbededType

services:
    btn_admin.form.handler.entiy_form:
        class: %btn_admin.form.handler.entiy_form.class%
        arguments:
            em: @doctrine.orm.entity_manager

    btn_admin.entity_form_handler: @btn_admin.form.handler.entiy_form

    btn_admin.form.handler.entiy_form.request_aware:
        class: %btn_admin.form.handler.entiy_form.request_aware.class%
        scope: request
        arguments:
            em: @doctrine.orm.entity_manager
            request: @?request

    btn_admin.form_handler: @btn_admin.form.handler.entiy_form.request_aware

    btn_admin.form.abstract:
        abstract: true
        calls:
            - [setAssetLoader, ['@btn_base.asset_loader']]

    btn_admin.registration.form.type:
        class: Btn\AdminBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: btn_admin_user_add }

    btn_admin.profile.form.type:
        class: Btn\AdminBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: btn_admin_edit }

    btn_admin.form.button.create:
        class: %btn_admin.form.button.create.class%
        tags:
            - { name: form.type, alias: btn_create }

    btn_admin.form.button.delete:
        class: %btn_admin.form.button.delete.class%
        calls:
            - [setTranslator, ['@translator']]
        tags:
            - { name: form.type, alias: btn_delete }

    btn_admin.form.button.save:
        class: %btn_admin.form.button.save.class%
        tags:
            - { name: form.type, alias: btn_save }

    btn_admin.form.button.update:
        class: %btn_admin.form.button.update.class%
        tags:
            - { name: form.type, alias: btn_update }

    btn_admin.form.type.color:
        class: %btn_admin.form.type.color.class%
        calls:
            - [setAssetLoader, ['@btn_base.asset_loader']]
        tags:
            - { name: form.type, alias: btn_color }

    btn_admin.form.type.date_time:
        class: %btn_admin.form.type.date_time.class%
        calls:
            - [setAssetLoader, ['@btn_base.asset_loader']]
        tags:
            - { name: form.type, alias: btn_datetime }

    btn_admin.form.type.embeded:
        class: %btn_admin.form.type.embeded.class%
        calls:
            - [setAssetLoader, ['@btn_base.asset_loader']]
            - [setTranslator, ['@translator']]
        tags:
            - { name: form.type, alias: btn_embeded }
