parameters:
    btn_admin.form.handler.entiy_form.class: Btn\AdminBundle\Form\Handler\EntityFormHandler
    btn_admin.form.button.create.class: Btn\AdminBundle\Form\Button\CreateButton
    btn_admin.form.button.delete.class: Btn\AdminBundle\Form\Button\DeleteButton
    btn_admin.form.button.save.class: Btn\AdminBundle\Form\Button\SaveButton
    btn_admin.form.button.update.class: Btn\AdminBundle\Form\Button\UpdateButton
    btn_admin.form.type.color.class: Btn\AdminBundle\Form\Type\ColorType
    btn_admin.form.type.date_time.class: Btn\AdminBundle\Form\Type\DateTimeType
    btn_admin.form.type.date.class: Btn\AdminBundle\Form\Type\DateType
    btn_admin.form.type.embedded.class: Btn\AdminBundle\Form\Type\EmbeddedType
    btn_admin.form.type.slug.class: Btn\AdminBundle\Form\Type\SlugType
    btn_admin.form.type.hidden_entity.class: Btn\AdminBundle\Form\Type\HiddenEntityType
    btn_admin.form.user_control.class: Btn\AdminBundle\Form\UserControlForm
    btn_admin.form.profile_control.class: Btn\AdminBundle\Form\ProfileControlForm
    btn_admin.form.extension.text_type.class: Btn\AdminBundle\Form\Extension\TextTypeExtension
    btn_admin.form.extension.submit_type.class: Btn\AdminBundle\Form\Extension\SubmitTypeExtension
    btn_admin.form.extension.choice_type.class: Btn\AdminBundle\Form\Extension\ChoiceTypeExtension

services:
    # Handlers
    btn_admin.form.handler.entiy_form:
        class: %btn_admin.form.handler.entiy_form.class%
        arguments:
            em: @doctrine.orm.entity_manager

    btn_admin.entity_form_handler: @btn_admin.form.handler.entiy_form

    btn_admin.form_handler: @btn_admin.entity_form_handler

    btn_admin.form.handler.user_form:
        class: %btn_admin.form.handler.user_form.class%
        arguments:
            userManager: @fos_user.user_manager

    btn_admin.form.handler.user: @btn_admin.form.handler.user_form

    # Forms
    btn_admin.form.abstract:
        abstract: true
        calls:
            - [setAssetLoader, [@btn_base.asset_loader]]

    btn_admin.form.user_control:
        class: %btn_admin.form.user_control.class%
        parent: btn_admin.form.abstract
        calls:
            - [setClass, [%btn_admin.user.class%]]
        tags:
            - { name: form.type, alias: btn_admin_form_user_control }

    btn_admin.form.profile_control:
        class: %btn_admin.form.profile_control.class%
        parent: btn_admin.form.abstract
        calls:
            - [setClass, [%btn_admin.user.class%]]
        tags:
            - { name: form.type, alias: btn_admin_form_profile_control }

    # Types
    btn_admin.form.button.create:
        class: %btn_admin.form.button.create.class%
        tags:
            - { name: form.type, alias: btn_create }

    btn_admin.form.button.delete:
        class: %btn_admin.form.button.delete.class%
        calls:
            - [setTranslator, ['@translator']]
        tags:
            - { name: form.type, alias: btn_delete }

    btn_admin.form.button.save:
        class: %btn_admin.form.button.save.class%
        tags:
            - { name: form.type, alias: btn_save }

    btn_admin.form.button.update:
        class: %btn_admin.form.button.update.class%
        tags:
            - { name: form.type, alias: btn_update }

    btn_admin.form.type.color:
        class: %btn_admin.form.type.color.class%
        calls:
            - [setAssetLoader, [@btn_base.asset_loader]]
        tags:
            - { name: form.type, alias: btn_color }

    btn_admin.form.type.date_time:
        class: %btn_admin.form.type.date_time.class%
        calls:
            - [setAssetLoader, [@btn_base.asset_loader]]
        tags:
            - { name: form.type, alias: btn_datetime }

    btn_admin.form.type.date:
        class: %btn_admin.form.type.date.class%
        calls:
            - [setAssetLoader, [@btn_base.asset_loader]]
        tags:
            - { name: form.type, alias: btn_date }


    btn_admin.form.type.embedded:
        class: %btn_admin.form.type.embedded.class%
        calls:
            - [setAssetLoader, [@btn_base.asset_loader]]
            - [setTranslator, [@translator]]
        tags:
            - { name: form.type, alias: btn_embedded }

    btn_admin.form.type.slug:
        class: %btn_admin.form.type.slug.class%
        calls:
            - [setAssetLoader, [@btn_base.asset_loader]]
        tags:
            - { name: form.type, alias: btn_slug }

    btn_admin.form.type.hidden_entity:
        class: %btn_admin.form.type.hidden_entity.class%
        calls:
            - [setEntityManager, [@doctrine.orm.entity_manager]]
        tags:
            - { name: form.type, alias: btn_hidden_entity }

    # Extensions
    btn_admin.form.extension.text_type:
        class: %btn_admin.form.extension.text_type.class%
        tags:
            - { name: form.type_extension, alias: text }

    btn_admin.form.extension.submit_type:
        class: %btn_admin.form.extension.submit_type.class%
        tags:
            - { name: form.type_extension, alias: submit }

    btn_admin.form.extension.choice_type:
        class: %btn_admin.form.extension.choice_type.class%
        tags:
            - { name: form.type_extension, alias: choice }
