services:

    btn_admin.form.handler.entiy_form_handler:
        class: %btn_admin.form.handler.entiy_form_handler.class%
        scope: request
        arguments:
            em: @doctrine.orm.entity_manager
            request: @?request

    btn_admin.form_handler: '@btn_admin.form.handler.entiy_form_handler'

    btn_admin.registration.form.type:
        class: Btn\AdminBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: btn_admin_user_add }

    btn_admin.profile.form.type:
        class: Btn\AdminBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: btn_admin_edit }

    btn_admin.delete.form.type:
        class: Btn\AdminBundle\Form\Type\DeleteFormType
        tags:
            - { name: form.type, alias: btn_admin_delete }

    btn_admin.form.button.create:
        class: Btn\AdminBundle\Form\Button\BtnCreateButton
        tags:
            - { name: form.type, alias: btn_admin_create_button }

    btn_admin.form.button.delete:
        class: Btn\AdminBundle\Form\Button\BtnDeleteButton
        arguments:
            translator: @translator
        tags:
            - { name: form.type, alias: btn_admin_delete_button }

    btn_admin.form.button.save:
        class: Btn\AdminBundle\Form\Button\BtnSaveButton
        tags:
            - { name: form.type, alias: btn_admin_save_button }

    btn_admin.form.button.update:
        class: Btn\AdminBundle\Form\Button\BtnUpdateButton
        tags:
            - { name: form.type, alias: btn_admin_update_button }
