parameters:
    btn_admin.abstract_menu_builder.class: Btn\AdminBundle\Menu\AbstractMenuBuilder
    btn_admin.menu_builder.class: Btn\AdminBundle\Menu\MenuBuilder
    btn_admin.menu_item.class: Btn\AdminBundle\Menu\MenuItem
    btn_admin.provider.abstract_entity.class: Btn\AdminBundle\Provider\AbstractEntityProvider
    btn_admin.provider.entity.class: Btn\AdminBundle\Provider\EntityProvider
    btn_admin.event_listener.control_controller_listener.class: Btn\AdminBundle\EventListener\ControlControllerListener
