_btn_admin_routing_control:
    resource: "@BtnAdminBundle/Resources/config/routing/control.yml"
    prefix: /control

_btn_admin_routing_fos_user:
    resource: "@BtnAdminBundle/Resources/config/routing/fos_user.yml"
