services:

    btn_admin.abstract_menu_builder:
        class: %btn_admin.abstract_menu_builder_class%
        abstract: true
        arguments: ["@knp_menu.factory", "@translator"]

    btn_admin.menu_builder:
        class: %btn_admin.menu_builder_class%
        parent: btn_admin.abstract_menu_builder

    btn_admin.menu_navbar:
        class: %btn_admin.menu_item_class%
        factory_service: btn_admin.menu_builder
        factory_method: createMenu
        arguments: ["@request", "top_menu", "btn_admin_homepage", [], []]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: btn_admin.menu_navbar }

    btn_admin.menu_navbar.modules:
        class: %btn_admin.menu_item_class%
        factory_service: btn_admin.menu_builder
        factory_method: createMenu
        arguments: ["@request", "btn_admin.modules", "btn_admin_homepage", [], []]
        scope: request
        tags:
            - { name: btn_admin.menu_item , parent: btn_admin.menu_navbar }
