parameters:
    control_menu_nav_items: ~

services:
    btn_admin.menu_builder:
        class: Btn\AdminBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", "@translator"]

    btn_admin.menu_top:
        class: Knp\Menu\MenuItem
        factory_service: btn_admin.menu_builder
        factory_method: createMenu
        arguments: ["@request", "top_menu", "cp_homepage", [], []]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: btn_admin_menu_top }

    btn_admin.menu_top_modules:
        class: Knp\Menu\MenuItem
        factory_service: btn_admin.menu_builder
        factory_method: createMenu
        arguments: ["@request", "btn_admin.modules", "cp_homepage", [], []]
        scope: request
        tags:
            - { name: btn_admin_menu_item , parent: btn_admin.menu_top }
