parameters:
    btn_admin.event_listener.control_controller_listener.class: Btn\AdminBundle\EventListener\ControlControllerListener

services:
    btn_admin.provider.user:
        class: %btn_base.provider.entity.class%
        parent: btn_base.provider.abstract_entity
        arguments: [%btn_admin.user.class%]

    btn_admin.event_listener.control_controller_listener:
        class: %btn_admin.event_listener.control_controller_listener.class%
        arguments:
            annotationReader: @annotation_reader
            bundleHelper: @btn_base.helper.bundle
        calls:
            - [setPerPage, ['%btn_admin.list.per_page%']]
            - [setFormHandler, ['@btn_admin.form.handler.entiy_form']]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
