parameters:
    btn_admin.provider.entity.class: Btn\AdminBundle\Provider\EntityProvider
    btn_admin.provider.abstract_entity.class: Btn\AdminBundle\Provider\AbstractEntityProvider
    btn_admin.event_listener.control_controller_listener.class: Btn\AdminBundle\EventListener\ControlControllerListener

services:
    btn_admin.provider.abstract_entity:
        class: %btn_admin.provider.abstract_entity.class%
        abstract: true
        calls:
            - [setEntityManager, ['@doctrine.orm.entity_manager']]

    btn_admin.event_listener.control_controller_listener:
        class: %btn_admin.event_listener.control_controller_listener.class%
        arguments:
            annotationReader: @annotation_reader
            bundleHelper: @btn_base.helper.bundle
        calls:
            - [setPerPage, ['%btn_admin.list.per_page%']]
            - [setFormHandler, ['@btn_admin.form.handler.entiy_form']]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
