parameters:
    control_menu_nav_items: ~

services:
    btn_admin.menu_builder:
        class: Btn\AdminBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", "@translator"]

    btn_admin.menu.top:
        class: Knp\Menu\MenuItem
        factory_service: btn_admin.menu_builder
        factory_method: createTopMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: top_menu }

