ivory_ck_editor:
    default_config: btn_default
    configs:
        btn_default:
            stylesSet:
                -
                    name: Big
                    element: big
                -
                    name: Small
                    element: small
                -
                    name: Typewriter
                    element: tt
                -
                    name: Computer Code
                    element: code
                -
                    name: Keyboard Phrase
                    element: kbd
                -
                    name: 'Sample Text'
                    element: samp
                -
                    name: Variable
                    element: var
                -
                    name: 'Deleted Text'
                    element: del
                -
                    name: 'Inserted Text'
                    element: ins
                -
                    name: 'Cited Work'
                    element: cite
                -
                    name: 'Inline Quotation'
                    element: q
                -
                    name: 'Language: RTL'
                    element: span
                    attributes:
                        dir: rtl
                -
                    name: 'Language: LTR'
                    element: span
                    attributes:
                        dir: ltr
                -
                    name: 'Styled image (left)'
                    element: img
                    attributes:
                        class: left
                -
                    name: 'Styled image (right)'
                    element: img
                    attributes:
                        class: right
                -
                    name: 'Square Bulleted List'
                    element: ul
                    styles:
                        list-style-type: square
            toolbar:
                -
                    name: basicstyles
                    items:
                        - Bold
                        - Italic
                        - Underline
                        - Strike
                        - Subscript
                        - Superscript
                        - -
                        - RemoveFormat
                -
                    name: paragraph
                    items:
                        - NumberedList
                        - BulletedList
                        - -
                        - Outdent
                        - Indent
                        - -
                        - JustifyLeft
                        - JustifyCenter
                        - JustifyRight
                        - JustifyBlock
                -
                    name: links
                    items:
                        - Link
                        - Unlink
                        - Anchor
                -
                    name: insert
                    items:
                        - Image
                        - Table
                        - HorizontalRule
                        - Iframe
                -
                    name: document
                    items:
                        - Source
                        - Templates
                - /
                -
                    name: styles
                    items:
                        - Styles
                        - Format
                        - Font
                        - FontSize
                -
                    name: 'colors'
                    items: ['TextColor','BGColor']
            uiColor: '#ffffff'
            extraPlugins: 'iframe'
            language: %locale%
