parameters:
    btn_admin.abstract_menu_builder.class: Btn\AdminBundle\Menu\AbstractMenuBuilder
    btn_admin.menu_builder.class: Btn\AdminBundle\Menu\MenuBuilder
    btn_admin.menu_item.class: Btn\AdminBundle\Menu\MenuItem
    btn_admin.menu.extension.class: Btn\AdminBundle\Menu\MenuExtension

services:
    btn_admin.menu.extension:
        class: %btn_admin.menu.extension.class%
        public: false
        tags:
            - { name: knp_menu.factory_extension, priority: -20 }

    btn_admin.abstract_menu_builder:
        public: false
        class: %btn_admin.abstract_menu_builder.class%
        abstract: true
        arguments:
            - @knp_menu.factory
            - @translator
            - @?security.context

    btn_admin.menu_builder:
        class: %btn_admin.menu_builder.class%
        parent: btn_admin.abstract_menu_builder

    btn_admin.menu_navbar:
        class: %btn_admin.menu_item.class%
        factory_service: btn_admin.menu_builder
        factory_method: createMenu
        arguments: [@request, top_menu, btn_admin_defaultcontrol_index, [], []]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: btn_admin.menu_navbar }

    btn_admin.menu_navbar.modules:
        public: false
        class: %btn_admin.menu_item.class%
        factory_service: btn_admin.menu_builder
        factory_method: createMenu
        arguments: [@request, btn_admin.menu_navbar.modules.label, btn_admin_defaultcontrol_index, [], []]
        scope: request
        tags:
            - { name: btn_admin.menu_item , parent: btn_admin.menu_navbar }
