parameters:
    btn_admin.event_listener.control_controller_listener.class: Btn\AdminBundle\EventListener\ControlControllerListener
    btn_admin.event_listener.resetting_subscriber.class: Btn\AdminBundle\EventListener\ResettingSubscriber
    btn_admin.event_listener.index_state_store_subscriber.class: Btn\AdminBundle\EventListener\IndexStateStoreSubscriber
    btn_admin.routing.url_generator.class: Btn\AdminBundle\Routing\UrlGenerator

services:
    btn_admin.provider.user:
        class: %btn_base.provider.entity.class%
        parent: btn_base.provider.abstract_entity
        arguments: [%btn_admin.user.class%]

    btn_admin.event_listener.control_controller_listener:
        class: %btn_admin.event_listener.control_controller_listener.class%
        arguments:
            annotationReader: @annotation_reader
            bundleHelper: @btn_base.helper.bundle
        calls:
            - [setPerPage, ['%btn_admin.list.per_page%']]
            - [setFormHandler, ['@btn_admin.form.handler.entity_form']]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    btn_admin.event_listener.resetting_subscriber:
        class: %btn_admin.event_listener.resetting_subscriber.class%
        arguments:
            router: @router
        tags:
            - { name: kernel.event_subscriber }

    btn_admin.event_listener.index_state_store_subscriber:
        class: %btn_admin.event_listener.index_state_store_subscriber.class%
        tags:
            - { name: kernel.event_subscriber }

    btn_admin.routing.url_generator:
        class: %btn_admin.routing.url_generator.class%
        arguments:
            router: @router
            session: @session
