_btn_admin_routing_control_controller_default:
    resource: "@BtnAdminBundle/Controller/DefaultControlController.php"
    type:     annotation

_btn_admin_routing_control_controller_user:
    resource: "@BtnAdminBundle/Controller/UserControlController.php"
    type:     annotation

_btn_admin_routing_control_controller_profile:
    resource: "@BtnAdminBundle/Controller/ProfileControlController.php"
    type:     annotation
